chat box component added
Integrify-Team-4/Tindev-Frontend pull request #158
Opened 2021-01-29 11:40 UTC by dilippoudel

The component is not rendering inside chat tab, there is isssue.

2021-01-29 20:45 UTC, Tsaikkari commented
Import chat box to pages/JobseekerProfile and pages/CompanyProfile and pass the component as a prop into Tabs instance. Should work then.

2021-02-01 21:06 UTC, Wyfy0107 commented
Can we have some image here as well?

2021-02-05 18:33 UTC, Tsaikkari requested changes

2021-02-05 18:33 UTC, Tsaikkari commented on src/index.tsx
> +axios.defaults.baseURL = 'http://localhost:3000'
Change this back to heroku url.

2021-02-05 18:48 UTC, Tsaikkari approved these changes
Good.

2021-02-05 18:48 UTC, merged