Creating jobpost service (still on working/progress)
Integrify-Team-4/Tindev-Frontend pull request #66
Opened 2020-12-30 17:56 UTC by dilippoudel

2020-12-30 18:06 UTC, Nejo12 requested changes
Could you check and correct if the reverts can be done before merging?

2020-12-30 18:06 UTC, Nejo12 commented on src/pages/EditProfile/index.tsx
>          </Form.Label>
I think you did not accept the incoming changes in this file and This cleared everything I worked on today.  Kindly check if you can revert this file.

2020-12-30 18:06 UTC, Nejo12 commented on src/scss/_mobile.scss
> -
Same here as well.

2020-12-30 18:06 UTC, Nejo12 commented on src/scss/styles.scss
> -
Here too... :(

2021-01-04 14:10 UTC, closed without merging

2021-01-04 14:10 UTC, dilippoudel commented
out dated