Chat UI
Integrify-Team-4/Tindev-Frontend pull request #98
Opened 2021-01-06 20:23 UTC by khumair

2021-01-06 20:42 UTC, Tsaikkari requested changes
You have all the old code there, so you haven't pulled the latest code.

2021-01-06 20:47 UTC, Wyfy0107 requested changes

2021-01-06 20:47 UTC, Wyfy0107 commented on src/Routes.tsx
> +    <Route exact path="/company/profile1" component={CompanyHomePage} />
I believe these should be one page

2021-01-06 20:47 UTC, Wyfy0107 commented on src/components/JobPost/Tags.tsx
> +
If you're not using this component then you should remove it

2021-01-06 20:47 UTC, Wyfy0107 commented on src/components/JobPost/index.tsx
> +    // dispatch(creatingJobPostRequest(jobPosted))
Why commented ?

2021-01-07 17:58 UTC, Tsaikkari commented
@khumair I added your chatbox component to my pr with latest code. You can make a new branch and pull latest code from develop into it. After the pull, check out that you don't have any extra folders/files in it. Compare the team4 develop branch file structure to yours. Don't use this ChatUI branch anymore when you make a pr, because all the old code is there and we don't want to merge them. 

When you have pulled the new code to the new branch, make yet another branch and work on there, so that you have the previous branch "clean". Make a new pr as soon as you've made a new feature.

2021-01-09 09:29 UTC, khumair commented on src/components/JobPost/index.tsx
> +    // dispatch(creatingJobPostRequest(jobPosted))
it has some error , 
but now its fixed

2021-01-09 14:46 UTC, Wyfy0107 commented
@Tsaikkari Why did you reopen this pr, didn't you mere @khumair code to the previous pr ?

2021-01-09 16:24 UTC, Tsaikkari commented
@Wyfy0107 I copied and pasted the chatbox component into my repo and closed the pr, but I don't think it's a good and fair way to go. It's better to give him the chance to fix his own errors and learn properly how to use git and github in a team. I don't want him to miss that opportunity.

2021-01-11 08:29 UTC, closed without merging